### PR TITLE
Start of Game-Sync, BugFixes

### PR DESCRIPTION
**Pull request by BurrrY**
Fix: Error on launchers in SettingsDiag, Close AddGame-Diag after Add

### CODE REVIEW

**Comment by turtlehunter** [comment]
I think you should leave the debug messages

**Comment by turtlehunter** [comment]
+1 when lib is merged

**Comment by BurrrY** [comment]
There is the same Debug-Message in the Lib.

**Comment by turtlehunter** [comment]
Yeah, checked later :P

**Pull request merged**
