### PR TITLE
Added tabs, TODOs in Game List tab

### PR DESCRIPTION
**Pull request by turtlehunter**

### CODE REVIEW

**Comment by kamnxt** [comment]
in FusionClient.pro: it seems like you've added another place for the lib (build-LibFusion-Desktop_Qt_5_4_1_GCC_64bit-Debug/release/). Also, I don't think we should handle the adding of the games in another tab, but probably a dialog instead.

**Comment by turtlehunter** [comment]
Ok. And the .pro thing was created when testing :P

**Comment by Razzile** [comment]
I made a (kinda crappy) borderless UI. Unlike BorderlessWindow it is cross platform. We could build on it if you like http://prntscr.com/75sduc

**Comment by urielsalis** [comment]
Closing in favour of razzile idea

**Comment by turtlehunter** [comment]
Alt account FTW

**Pull request closed without merging**
